# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe68ba12c3323c3f7930ddbd1c98cd119f1c239cdc36edd2195f7f7439d93613a340f521fe4d8153355a0a96cb1708f0995fd26c00f78a1ed92e58c0262cb7d9

test:
  secret_key_base: e0ced9d30eb03b322a666083c792c1a22cccb12380bba6c7bd4bf211cb36b1c21a5ee37988e58cc83a070e033960cd056be252891067a608bfecd8424a2b3bfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
